version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - ENVIRONMENT=development
      - DATABASE_URL=postgresql://user:password@db:5432/askmydocs_db
      - REDIS_URL=redis://cache:6379/0
      - ELASTICSEARCH_HOST=elasticsearch
      - ELASTICSEARCH_PORT=9200
      # Add Elasticsearch credentials if security is enabled (X-Pack)
      # - ELASTICSEARCH_USERNAME=elastic
      # - ELASTICSEARCH_PASSWORD=changeme
      # Add environment variables for the embedding model if needed
      # - EMBEDDING_MODEL=sentence-transformers/all-MiniLM-L6-v2
    depends_on:
      - db
      - cache
      - elasticsearch
    networks:
      - app-network

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - REACT_APP_API_URL=http://localhost:8000
    depends_on:
      - backend
    networks:
      - app-network

  db:
    # image: pgvector/pgvector:0.5.1
    image: ankane/pgvector:latest
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=askmydocs_db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    networks:
      - app-network

  cache:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - app-network

  elasticsearch:
    image: elasticsearch:7.17.10 # Use a compatible version
  
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - es_data:/usr/share/elasticsearch/data
    environment:
      - discovery.type=single-node
      # Disable security for simplicity in local development
      - xpack.security.enabled=false
      - xpack.security.enrollment.enabled=false
      - xpack.security.http.ssl.enabled=false
    networks:
      - app-network

volumes:
  db_data:
  es_data:

networks:
  app-network:
    driver: bridge 